export { default as BootScene } from './Boot'
export { default as CreditsScene } from './Credits'
export { default as MenuScene } from './Menu'
export { default as WinScene } from './Win'
export * from './GameScenes'
